version: "3.9"

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: quickcart
      POSTGRES_USER: quickcart
      POSTGRES_PASSWORD: quickcart123
    ports:
      - "5432:5432"