services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      POSTGRES_DB: quickcart
      POSTGRES_USER: quickcart_user
      POSTGRES_PASSWORD: quickcart123
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: quickcart
      POSTGRES_USER: quickcart_user
      POSTGRES_PASSWORD: quickcart123
    ports:
      - "5432:5432"
